apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.AppName }}-secret
  namespace: {{ .Values.NameSpace }}
type: Opaque
data:
  mysql-root-password: {{ randAlphaNum 32 | b64enc }}
  mysql-database: {{ .Values.MariadbDbName | b64enc }}
  mysql-user: {{ .Values.MariadbDbUser | b64enc }}
  mysql-password: {{ randAlphaNum 32 | b64enc }}